secrets:
  db_password:
    file: "db_password.txt"

services:
  product-service:
    build: app
    volumes:
      - "./db/db.ini:/main/config/db.ini"
      - "./app/src:/main"
    secrets:
      - db_password
    networks:
      - frontend
      - backend
    environment:
      - DEBUG=True

  web:
    build: nginx
    ports:
      - "80:80"
    networks:
      - frontend

  db:
    image: mysql
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
      - "db-volume:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backend

volumes:
  db-volume:

networks:
  frontend:
  backend:
